[Main]
backurl = "https://weepingdogel.github.io/"
[friends]
number = 16
    [friends.1]
    Avatar = "https://avatars.githubusercontent.com/u/440661"
    Title = "ä¾äº‘'s Blog"
    URL = "https://blog.lilydjwg.me/"
    Bio = "Happy coding, happy living!"
    [friends.2]
    Avatar = "https://avatars.githubusercontent.com/u/34574198"
    Title = "æçš“å¥‡"
    URL = "https://liolok.com/zhs/"
    Bio = "å²‚æœ‰æ–‡ç« å€¾ç¤¾ç¨·ï¼Œä»æ¥ä½å¹¸è¦†ä¹¾å¤ã€‚"
    [friends.3]
    Avatar = "https://avatars.githubusercontent.com/u/32677240"
    Title = "Esonhugh's Blog"
    URL = "https://esonhugh.me/"
    Bio = "__æ¸…é—²æ‚ å“‰å¿«æ´»æ—¥ï¼Œä¿¯é¦–ä¸é—®ä¸–é—´äº‹ã€‚"
    [friends.4]
    Avatar = "https://avatars.githubusercontent.com/u/70447830"
    Title = "CRZY ZONE"
    URL = "https://crzy233.github.io/"
    Bio = "_æ— å¯å¥‰å‘Šã€‚"
    [friends.5]
    Avatar = "https://avatars.githubusercontent.com/u/54034088"
    Title = "mushin2kçš„åšå®¢"
    URL = "https://mushin2k.github.io/"
    Bio = "ä¸€èˆ¬åˆ·æœºçˆ±å¥½è€…å…¼éŸ³æ¸¸ä¼‘é—²ç©å®¶ï¼Œå¶å°”ç©æ–‡å…·ï¼Œåšå®¢ä¸å¸¸æ›´æ–° éŸ³ã‚²ãƒ¼å¤§å¥½ãï¼ˆ"
    [friends.6]
    Avatar = "https://avatars.githubusercontent.com/u/61851016"
    Title = "Piggy's Blog"
    URL = "https://blog.piggy.moe/"
    Bio = "Piggyâ€™s random stuff"
    [friends.7]
    Avatar = "https://avatars.githubusercontent.com/u/54669781"
    Title = "æ¬ é™¥é›»æ°—ã®æ‘¸é±¼å°æ± "
    URL = "https://blog.atri.tk/"
    Bio = "åˆ’æ°´æ‘¸é±¼æœ€å¿«ä¹å•¦ï½å†™blogä»€ä¹ˆçš„æ‰ä¸è¦å‘¢"
    [friends.8]
    Avatar = "https://avatars.githubusercontent.com/u/59352355"
    Title = "111çš„ Blog"
    URL = "https://lzwsb.github.io/"
    Bio = " "
    [friends.9]
    Avatar = "https://avatars.githubusercontent.com/u/54489701"
    Title = "zhyjc6's Blog"
    URL = "https://zhyjc6.github.io/"
    Bio = " "
    [friends.10]
    Avatar = "https://avatars.githubusercontent.com/u/78380885"
    Title = "å®‰äº•é½æ¡œçš„æ–‡å­¦å°å±‹"
    URL = "https://zangjiucheng.wixsite.com/website-project"
    Bio = "ã€Šå¸¸è­˜ã€‹ä¸å¯ä¸è®€ä¹Ÿã€‚"
    [friends.11]
    Avatar = "https://avatars.githubusercontent.com/u/12439321"
    Title = "â‘¨BIE"
    URL = "https://9bie.org/"
    Bio = "ä¼ªæŠ€æœ¯å®…çš„è¿·ä¹‹åœ°"
    [friends.12]
    Avatar = "https://avatars.githubusercontent.com/u/17158086"
    Title = "YuutaW çš„è‡ªè¨€è¯­"
    URL = "https://blog.yuuta.moe/"
    Bio = "ä¸€ä¸ªèŒæ–°åœ¨æ¢ç´¢ä¸–ç•Œçš„é“è·¯ä¸Šç•™ä¸‹çš„äº›è®¸è§è§£"
    [friends.13]
    Avatar = "https://ci.cncn3.cn/b14f1cc92b39a12e69a4fe62b4dbcc41.png"
    Title = "è¡€ç‰™çš„ä¸ªäººåšå®¢"
    URL = "https://xueya.me/"
    Bio = "è¡€ç‰™ï¼Œ04å¹´ï¼Œä¸¥é‡ä¸­äºŒç—…"
    [friends.14]
    Avatar = "https://avatars.githubusercontent.com/u/36183551"
    Title = "æ¬§å¼çš„Blog"
    URL = "https://blog.ous50.moe"
    Bio = "æ¥å‘€ï¼Œæ¥ç©å‘€~"
    [friends.15]
    Avatar = "https://avatars.githubusercontent.com/u/36557882"
    Title = "æˆ‘ğŸæ²¡äº†"
    URL = "https://kekeimiku.github.io/"
    Bio = "Everything is game."
    [friends.16]
    Avatar = "https://avatars.githubusercontent.com/u/36188023"
    Title = "KiraPGR's Blog"
    URL = "https://kira-pgr.github.io/"
    Bio = "/* Life Runs On Code */"